{
  "dataType": "CVE_RECORD",
  "containers": {
    "adp": [
      {
        "title": "CISA ADP Vulnrichment",
        "metrics": [
          {
            "other": {
              "type": "ssvc",
              "content": {
                "id": "CVE-2024-38525",
                "role": "CISA Coordinator",
                "options": [
                  {
                    "Exploitation": "none"
                  },
                  {
                    "Automatable": "yes"
                  },
                  {
                    "Technical Impact": "partial"
                  }
                ],
                "version": "2.0.3",
                "timestamp": "2024-07-02T15:43:21.179262Z"
              }
            }
          }
        ],
        "affected": [
          {
            "cpes": [
              "cpe:2.3:a:datadoghq:dd-trace-cpp:*:*:*:*:*:*:*:*"
            ],
            "vendor": "datadoghq",
            "product": "dd-trace-cpp",
            "versions": [
              {
                "status": "affected",
                "version": "0",
                "lessThan": "0.1.13",
                "versionType": "custom"
              },
              {
                "status": "affected",
                "version": "0",
                "lessThan": "0.2.2",
                "versionType": "custom"
              }
            ],
            "defaultStatus": "unknown"
          }
        ],
        "providerMetadata": {
          "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
          "shortName": "CISA-ADP",
          "dateUpdated": "2024-07-02T15:51:03.855Z"
        }
      }
    ],
    "cna": {
      "title": "dd-trace-cpp malformed unicode header values may cause crash",
      "source": {
        "advisory": "GHSA-rf3p-mg22-qv6w",
        "discovery": "UNKNOWN"
      },
      "metrics": [
        {
          "cvssV3_1": {
            "scope": "UNCHANGED",
            "version": "3.1",
            "baseScore": 7.5,
            "attackVector": "NETWORK",
            "baseSeverity": "HIGH",
            "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "integrityImpact": "NONE",
            "userInteraction": "NONE",
            "attackComplexity": "LOW",
            "availabilityImpact": "HIGH",
            "privilegesRequired": "NONE",
            "confidentialityImpact": "NONE"
          }
        }
      ],
      "affected": [
        {
          "vendor": "DataDog",
          "product": "dd-trace-cpp",
          "versions": [
            {
              "status": "affected",
              "version": ">= 0.1.12, < 0.2.2"
            }
          ]
        }
      ],
      "references": [
        {
          "url": "https://github.com/DataDog/dd-trace-cpp/security/advisories/GHSA-rf3p-mg22-qv6w",
          "name": "https://github.com/DataDog/dd-trace-cpp/security/advisories/GHSA-rf3p-mg22-qv6w",
          "tags": [
            "x_refsource_CONFIRM"
          ]
        },
        {
          "url": "https://github.com/DataDog/dd-trace-cpp/releases/tag/v0.2.2",
          "name": "https://github.com/DataDog/dd-trace-cpp/releases/tag/v0.2.2",
          "tags": [
            "x_refsource_MISC"
          ]
        }
      ],
      "descriptions": [
        {
          "lang": "en",
          "value": "dd-trace-cpp is the Datadog distributed tracing for C++. When the library fails to extract trace context due to malformed unicode, it logs the list of audited headers and their values using the `nlohmann` JSON library. However, due to the way the JSON library is invoked, it throws an uncaught exception, which results in a crash. This vulnerability has been patched in version 0.2.2."
        }
      ],
      "problemTypes": [
        {
          "descriptions": [
            {
              "lang": "en",
              "type": "CWE",
              "cweId": "CWE-20",
              "description": "CWE-20: Improper Input Validation"
            }
          ]
        },
        {
          "descriptions": [
            {
              "lang": "en",
              "type": "CWE",
              "cweId": "CWE-248",
              "description": "CWE-248: Uncaught Exception"
            }
          ]
        }
      ],
      "providerMetadata": {
        "orgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
        "shortName": "GitHub_M",
        "dateUpdated": "2024-06-28T21:10:57.138Z"
      }
    }
  },
  "cveMetadata": {
    "cveId": "CVE-2024-38525",
    "state": "PUBLISHED",
    "dateUpdated": "2024-07-02T15:54:07.148Z",
    "dateReserved": "2024-06-18T16:37:02.728Z",
    "assignerOrgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
    "datePublished": "2024-06-28T21:10:57.138Z",
    "assignerShortName": "GitHub_M"
  },
  "dataVersion": "5.1"
}