{
  "dataType": "CVE_RECORD",
  "containers": {
    "adp": [
      {
        "title": "CISA ADP Vulnrichment",
        "metrics": [
          {
            "other": {
              "type": "ssvc",
              "content": {
                "id": "CVE-2023-30996",
                "role": "CISA Coordinator",
                "options": [
                  {
                    "Exploitation": "none"
                  },
                  {
                    "Automatable": "yes"
                  },
                  {
                    "Technical Impact": "partial"
                  }
                ],
                "version": "2.0.3",
                "timestamp": "2024-07-12T22:30:05.240318Z"
              }
            }
          }
        ],
        "affected": [
          {
            "cpes": [
              "cpe:2.3:a:ibm:cognos_analytics:11.1.7:-:*:*:*:*:*:*",
              "cpe:2.3:a:ibm:cognos_analytics:11.2.4:-:*:*:*:*:*:*",
              "cpe:2.3:a:ibm:cognos_analytics:12.0.0:*:*:*:*:*:*:*"
            ],
            "vendor": "ibm",
            "product": "cognos_analytics",
            "versions": [
              {
                "status": "affected",
                "version": "11.1.7"
              },
              {
                "status": "affected",
                "version": "11.2.4"
              },
              {
                "status": "affected",
                "version": "12.0.0"
              }
            ],
            "defaultStatus": "unaffected"
          }
        ],
        "providerMetadata": {
          "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
          "shortName": "CISA-ADP",
          "dateUpdated": "2024-07-12T22:32:15.750Z"
        }
      }
    ],
    "cna": {
      "title": "IBM Cognos Analytics cross-origin resource sharing",
      "source": {
        "discovery": "UNKNOWN"
      },
      "metrics": [
        {
          "format": "CVSS",
          "cvssV3_1": {
            "scope": "UNCHANGED",
            "version": "3.1",
            "baseScore": 5.3,
            "attackVector": "NETWORK",
            "baseSeverity": "MEDIUM",
            "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
            "integrityImpact": "NONE",
            "userInteraction": "NONE",
            "attackComplexity": "LOW",
            "availabilityImpact": "NONE",
            "privilegesRequired": "NONE",
            "confidentialityImpact": "LOW"
          },
          "scenarios": [
            {
              "lang": "en",
              "value": "GENERAL"
            }
          ]
        }
      ],
      "affected": [
        {
          "vendor": "IBM",
          "product": "Cognos Analytics",
          "versions": [
            {
              "status": "affected",
              "version": "11.1.7, 11.2.4, 12.0.0"
            }
          ],
          "defaultStatus": "unaffected"
        }
      ],
      "references": [
        {
          "url": "https://www.ibm.com/support/pages/node/7123154",
          "tags": [
            "vendor-advisory"
          ]
        },
        {
          "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/254290",
          "tags": [
            "vdb-entry"
          ]
        },
        {
          "url": "https://security.netapp.com/advisory/ntap-20240405-0004/"
        },
        {
          "url": "https://security.netapp.com/advisory/ntap-20240621-0006/"
        }
      ],
      "x_generator": {
        "engine": "Vulnogram 0.1.0-dev"
      },
      "descriptions": [
        {
          "lang": "en",
          "value": "IBM Cognos Analytics 11.1.7, 11.2.4, and 12.0.0 could be vulnerable to information leakage due to unverified sources in messages sent between Windows objects of different origins.  IBM X-Force ID:  254290.",
          "supportingMedia": [
            {
              "type": "text/html",
              "value": "IBM Cognos Analytics 11.1.7, 11.2.4, and 12.0.0 could be vulnerable to information leakage due to unverified sources in messages sent between Windows objects of different origins.  IBM X-Force ID:  254290.",
              "base64": false
            }
          ]
        }
      ],
      "problemTypes": [
        {
          "descriptions": [
            {
              "lang": "en",
              "type": "CWE",
              "cweId": "CWE-346",
              "description": "CWE-346 Origin Validation Error"
            }
          ]
        }
      ],
      "providerMetadata": {
        "orgId": "9a959283-ebb5-44b6-b705-dcc2bbced522",
        "shortName": "ibm",
        "dateUpdated": "2024-02-24T15:35:48.371Z"
      }
    }
  },
  "cveMetadata": {
    "cveId": "CVE-2023-30996",
    "state": "PUBLISHED",
    "dateUpdated": "2024-07-12T22:32:20.693Z",
    "dateReserved": "2023-04-21T17:49:51.826Z",
    "assignerOrgId": "9a959283-ebb5-44b6-b705-dcc2bbced522",
    "datePublished": "2024-02-24T15:35:48.371Z",
    "assignerShortName": "ibm"
  },
  "dataVersion": "5.1"
}