{
  "dataType": "CVE_RECORD",
  "dataVersion": "5.1",
  "cveMetadata": {
    "cveId": "CVE-2024-1141",
    "assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
    "state": "PUBLISHED",
    "assignerShortName": "redhat",
    "dateReserved": "2024-02-01T00:47:57.686Z",
    "datePublished": "2024-02-01T14:21:37.758Z",
    "dateUpdated": "2024-06-04T18:00:46.862Z"
  },
  "containers": {
    "cna": {
      "title": "Glance-store: glance store access key logged in debug log level",
      "metrics": [
        {
          "other": {
            "content": {
              "value": "Moderate",
              "namespace": "https://access.redhat.com/security/updates/classification/"
            },
            "type": "Red Hat severity rating"
          }
        },
        {
          "cvssV3_1": {
            "attackComplexity": "LOW",
            "attackVector": "LOCAL",
            "availabilityImpact": "NONE",
            "baseScore": 5.5,
            "baseSeverity": "MEDIUM",
            "confidentialityImpact": "HIGH",
            "integrityImpact": "NONE",
            "privilegesRequired": "LOW",
            "scope": "UNCHANGED",
            "userInteraction": "NONE",
            "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
            "version": "3.1"
          },
          "format": "CVSS"
        }
      ],
      "descriptions": [
        {
          "lang": "en",
          "value": "A vulnerability was found in python-glance-store. The issue occurs when the package logs the access_key for the glance-store when the DEBUG log level is enabled."
        }
      ],
      "affected": [
        {
          "vendor": "Red Hat",
          "product": "Red Hat OpenStack Platform 17.1 for RHEL 9",
          "collectionURL": "https://access.redhat.com/downloads/content/package-browser/",
          "packageName": "python-glance-store",
          "defaultStatus": "affected",
          "versions": [
            {
              "version": "0:2.5.1-17.1.20230621023901.el9ost",
              "lessThan": "*",
              "versionType": "rpm",
              "status": "unaffected"
            }
          ],
          "cpes": [
            "cpe:/a:redhat:openstack:17.1::el9"
          ]
        },
        {
          "vendor": "Red Hat",
          "product": "Red Hat OpenStack Platform 16.1",
          "collectionURL": "https://access.redhat.com/downloads/content/package-browser/",
          "packageName": "python-glance-store",
          "defaultStatus": "unknown",
          "cpes": [
            "cpe:/a:redhat:openstack:16.1"
          ]
        },
        {
          "vendor": "Red Hat",
          "product": "Red Hat OpenStack Platform 16.2",
          "collectionURL": "https://access.redhat.com/downloads/content/package-browser/",
          "packageName": "python-glance-store",
          "defaultStatus": "unknown",
          "cpes": [
            "cpe:/a:redhat:openstack:16.2"
          ]
        }
      ],
      "references": [
        {
          "url": "https://access.redhat.com/errata/RHSA-2024:2732",
          "name": "RHSA-2024:2732",
          "tags": [
            "vendor-advisory",
            "x_refsource_REDHAT"
          ]
        },
        {
          "url": "https://access.redhat.com/security/cve/CVE-2024-1141",
          "tags": [
            "vdb-entry",
            "x_refsource_REDHAT"
          ]
        },
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2258836",
          "name": "RHBZ#2258836",
          "tags": [
            "issue-tracking",
            "x_refsource_REDHAT"
          ]
        }
      ],
      "datePublic": "2024-01-17T00:00:00+00:00",
      "problemTypes": [
        {
          "descriptions": [
            {
              "cweId": "CWE-779",
              "description": "Logging of Excessive Data",
              "lang": "en",
              "type": "CWE"
            }
          ]
        }
      ],
      "x_redhatCweChain": "CWE-779: Logging of Excessive Data",
      "workarounds": [
        {
          "lang": "en",
          "value": "Avoid leaving the DEBUG log level enabled in critical environments."
        }
      ],
      "timeline": [
        {
          "lang": "en",
          "time": "2024-01-17T00:00:00+00:00",
          "value": "Reported to Red Hat."
        },
        {
          "lang": "en",
          "time": "2024-01-17T00:00:00+00:00",
          "value": "Made public."
        }
      ],
      "credits": [
        {
          "lang": "en",
          "value": "Red Hat would like to thank Lujie (ICT) for reporting this issue."
        }
      ],
      "providerMetadata": {
        "orgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "shortName": "redhat",
        "dateUpdated": "2024-05-22T21:45:05.759Z"
      }
    },
    "adp": [
      {
        "metrics": [
          {
            "other": {
              "type": "ssvc",
              "content": {
                "id": "CVE-2024-1141",
                "role": "CISA Coordinator",
                "options": [
                  {
                    "Exploitation": "none"
                  },
                  {
                    "Automatable": "no"
                  },
                  {
                    "Technical Impact": "partial"
                  }
                ],
                "version": "2.0.3",
                "timestamp": "2024-02-01T20:50:59.471008Z"
              }
            }
          }
        ],
        "providerMetadata": {
          "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
          "shortName": "CISA-ADP",
          "dateUpdated": "2024-04-29T17:57:33.644Z"
        },
        "title": "CISA ADP Vulnrichment"
      }
    ]
  }
}